# Generated by Django 5.1.4 on 2024-12-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
    ]
