# Generated by Django 5.1.4 on 2024-12-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_notes_note_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='notes',
        ),
    ]
