# Generated by Django 5.1.4 on 2024-12-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_servernote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerNote',
        ),
    ]
